### ISSUE TITLE
how to set the fix running speed of marquee

### ISSUE THREAD

**Issue by dennischchch** [megasanjay/vue3-marquee#29]
the speed is normal if small amount of item in marquee, however, it run faster if more items in the marquee, , is it possible to set the fix running speed of the item?
I also tried to set the duration in code, it still moved faster if there are large amount of item in the marquee

**Comment by megasanjay** [comment]
Hi @dennischchch 
The `speed` in this instance is technically the duration of the animation. Do you know the number of items inside the marquee? If you do you can set up a ratio so that the duration scales according to the number of elements.

An example is provided here: https://codesandbox.io/s/issue-29-h0piwd?file=/src/App.vue
It does rely on you knowing the number of elements inside the marquee. You could also use a width of the element based ratio if that works for your usecase.
